DEFAULT_GOOGLE_SCOPES = [
            'https://www.googleapis.com/auth/spreadsheets',
            'https://www.googleapis.com/auth/drive',
        ]
DEFAULT_GOOGLE_SHEET_VALUE_INPUT_OPTION="USER_ENTERED"
DEFAULT_GOOGLE_SHEET_RANGE_NAME="A1:D1"
DEFAULT_GOOGLE_SHEET_COMPLETE_RANGE_NAME="Sheet1!A1:D1000"
GOOGLE_SHEETS_SERVICE_NAME="sheets"
GOOGLE_SHEETS_SERVICE_VERSION="v4"
GOOGLE_DRIVE_SERVICE_NAME="drive"
GOOGLE_DRIVE_SERVICE_VERSION="v3"
SERVICE_ACCOUNT_FILE = 'credentials/primera.json'
DEFAULT_TIMEZONE="America/Argentina/Buenos_Aires"